Repository RickLeinecker/Fortuna, pull requests merged in 2019-12, with the labels that each got.

#28 Created and Updated Bug Report/Feature Request templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: sd tasks

#31 Merge Casus Highlighting on Click
  fortuna/.gitignore
  fortuna/package.json
  fortuna/src/casus/CasusEditor.js
  fortuna/src/casus/blocks/BinaryOperationBlock.js
  fortuna/src/casus/blocks/BoundingBox.js
  fortuna/src/casus/blocks/CasusBlock.js
  fortuna/src/casus/blocks/ContainerBlock.js
  fortuna/src/casus/blocks/EmptyBlock.js
  fortuna/src/casus/blocks/ForBlock.js
  fortuna/src/casus/blocks/SetVariableBlock.js
  fortuna/src/casus/blocks/VariableBlock.js
  fortuna/src/casus/blocks/generateCornerPerim.js
  fortuna/src/index.js
Labels: casus

#33 Feature/update issue templates add pr template
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/pull_request_template.md
Labels: sd tasks, workflow

#35 Jorge
  fortuna/package.json
  fortuna/src/LoginPopup.js
  fortuna/src/backend/server.js
  fortuna/src/login/Login.js
Labels: front-end

#34 Db/update db models post sd1
  fortuna/src/models/casusBlockModel.js
  fortuna/src/models/componentModel.js
  fortuna/src/models/marketSaleModel.js
  fortuna/src/models/tankModel.js
  fortuna/src/models/userModel.js
Labels: database

#42 Workflow/update compilation with babel
  fortuna/.babelrc
  fortuna/.bablerc
  fortuna/package.json
  fortuna/src/models/casusBlockModel.js
  fortuna/src/models/componentModel.js
  fortuna/src/models/marketSaleModel.js
  fortuna/src/models/tankModel.js
  fortuna/src/models/userModel.js
Labels: workflow
