Repository RickLeinecker/Fortuna, pull requests merged in 2020-04, with the labels that each got.

#345 Initial confirmation emails are sent again. Sorry everyone!
  src/backend/controllers/userController.js
Labels: api

#353 Reorganized file structure.
  src/armory/Armory.js
  src/armory/CreateNewTankPopup.js
  src/armory/RenameTankPopup.js
  src/armory/SelectTank.js
  src/armory/SetWagerPopup.js
  src/battlearena/BattleArena.js
  src/battlearena/ChallengePlayerPopup.js
  src/battlearena/Replays.js
  src/battlearena/SearchPlayers.js
  src/battleground/Battleground.js
  src/battleground/getReturnToFromBattlegroundLink.js
  src/battleground/getTanksToFightOnBattleground.js
  src/battleground/setReturnToFromBattlegroundLink.js
  src/casus/CasusContainer.js
  src/globalComponents/GetInventoryInfo.js
  src/globalComponents/Leaderboard.js
  src/globalComponents/Navbar.js
  src/globalComponents/SelectTank.js
  src/globalComponents/apiCalls/getAllUsersAPICall.js
  src/globalComponents/apiCalls/getBotTanksAPICall.js
  src/globalComponents/apiCalls/getMatchAPICall.js
  src/globalComponents/apiCalls/getReplayListAPICall.js
  src/globalComponents/apiCalls/getUserAPICall.js
  src/globalComponents/apiCalls/prepareMatchAPICall.js
  src/globalComponents/apiCalls/reportMatchResultAPICall.js
  src/globalComponents/apiCalls/tankAPIIntegration.js
  src/globalComponents/apiCalls/userAPIIntegration.js
  src/globalComponents/apiCalls/verifyLogin.js
  src/globalComponents/typesAndClasses/Component.js
  src/globalComponents/typesAndClasses/ComponentType.js
  src/globalComponents/typesAndClasses/LinkType.js
  src/globalComponents/typesAndClasses/Replay.js
  src/globalComponents/typesAndClasses/TankComponent.js
  src/globalComponents/typesAndClasses/User.js
  src/globalComponents/verifyLink.js
  src/login/Login.js
  src/mainmenu/MainMenu.js
  src/marketplace/ListingsView.js
  src/marketplace/MakeAComponentSaleView.js
  src/marketplace/MakeATankSaleView.js
  src/marketplace/Marketplace.js
  src/tanks/BackendTank.js
  src/tanks/Chassis.js
  src/tanks/Gun.js
  src/tanks/Jammer.js
  src/tanks/Scanner.js
  src/tanks/Tank.js
  src/tanks/TankDisplay.js
  src/tanks/TankLoader.js
  src/tanks/TankPart.js
  src/tanks/Treads.js
  src/trainingarena/TrainingArena.js
Labels: documentation

#351 Initial test setup and initial test for user model
  .babelrc
  .github/pull_request_template.md
  README.md
  src/backend/controllers/battleController.js
  src/backend/controllers/verifyController.js
  src/backend/expressApp.js
  src/backend/server.js
  src/models/userModel.test.js
Labels: testing, workflow

#355 Modify edit user API to not support editing usernames
  .github/pull_request_template.md
  README.md
  src/backend/controllers/userController.js
  src/backend/routes/userRoutes.js
Labels: api

#361 Model revamp to use ObjectId types for related fields.
  src/backend/controllers/marketController.js
  src/backend/controllers/tankController.js
  src/backend/routes/marketRoutes.js
  src/backend/routes/tankRoutes.js
  src/models/casusBlockModel.js
  src/models/componentModel.js
  src/models/marketSaleModel.js
  src/models/tankModel.js
  src/models/userModel.js
Labels: api, back-end

#362 Updated the website's style
  src/App.js
  src/Main.css
  src/armory/Armory.css
  src/armory/Armory.js
  src/armory/CreateNewTankPopup.js
  src/armory/DeleteTankPopup.js
  src/armory/RenameTankPopup.js
  src/armory/SetWagerPopup.js
  src/backend/controllers/userController.js
  src/battlearena/BattleArena.css
  src/battlearena/BattleArena.js
  src/battlearena/ChallengePlayerPopup.js
  src/battlearena/Replays.js
  src/battlearena/SearchPlayers.js
  src/globalComponents/Leaderboard.js
  src/globalComponents/SelectTank.js
  src/login/Login.css
  src/login/Login.js
  src/mainmenu/MainMenu.js
  src/marketplace/MakeAComponentSaleView.js
  src/marketplace/MakeATankSaleView.js
  src/marketplace/Marketplace.css
  src/marketplace/Marketplace.js
  src/tanks/TankDisplay.js
  src/trainingarena/TrainingArena.js
Labels: front-end

#376 Added 3v3 model updates
  src/models/battleRecordModel.js
  src/models/userModel.js
Labels: back-end

#377 Leaderboard route gets users with exception to master account.
  src/backend/controllers/userController.js
Labels: api

#381 Added onWagerUpdate function that reloads the navbar
  src/armory/Armory.js
  src/armory/SetWagerPopup.js
Labels: front-end

#380 Added a few lines to remove the favorite tank from make a tank sale list
  src/marketplace/MakeATankSaleView.js
Labels: front-end

#379 Malformed JWT error no longer shows up unnecessarily
  src/globalComponents/apiCalls/verifyLogin.js
Labels: front-end

#385 Remove favorite tank button added to Armory
  src/Main.css
  src/armory/Armory.css
  src/armory/Armory.js
  src/armory/SetWagerPopup.js
  src/backend/controllers/tankController.js
  src/backend/routes/tankRoutes.js
  src/globalComponents/apiCalls/tankAPIIntegration.js
Labels: api, front-end

#383 Casus Recolor Built in Variables and Prompt previously used Variables
  src/armory/Armory.js
  src/casus/CasusEditor.js
  src/casus/blocks/CasusBlock.js
  src/casus/blocks/GetVariableBlock.js
  src/casus/blocks/SetVariableBlock.js
  src/casus/userInteraction/SelectVariablePopup.js
  src/casus/userInteraction/defaultVariableNames.js
Labels: casus, front-end

#387 Made armory show the name of the tank being edited by Casus in the navbar
  src/casus/CasusContainer.js
  src/casus/CasusEditor.js
  src/casus/loadCasus.js
Labels: casus, front-end

#386 Made Casus stop executing after 50,000 statements per frame
  src/casus/blocks/AndBlock.js
  src/casus/blocks/CasusBlock.js
  src/casus/blocks/ContainerBlock.js
  src/casus/blocks/DoubleAbsBlock.js
  src/casus/blocks/DoubleAddBlock.js
  src/casus/blocks/DoubleDivideBlock.js
  src/casus/blocks/DoubleEqualsBlock.js
  src/casus/blocks/DoubleGreaterThanBlock.js
  src/casus/blocks/DoubleGreaterThanOrEqualBlock.js
  src/casus/blocks/DoubleLessThanBlock.js
  src/casus/blocks/DoubleLessThanOrEqualBlock.js
  src/casus/blocks/DoubleMaxBlock.js
  src/casus/blocks/DoubleMinBlock.js
  src/casus/blocks/DoubleMultiplyBlock.js
  src/casus/blocks/DoubleRoundBlock.js
  src/casus/blocks/DoubleSubtractBlock.js
  src/casus/blocks/DoubleTruncateBlock.js
  src/casus/blocks/ForBlock.js
  src/casus/blocks/GetListAtBlock.js
  src/casus/blocks/IfBlock.js
  src/casus/blocks/IfElseBlock.js
  src/casus/blocks/IntAbsBlock.js
  src/casus/blocks/IntAddBlock.js
  src/casus/blocks/IntDivideBlock.js
  src/casus/blocks/IntEqualsBlock.js
  src/casus/blocks/IntGreaterThanBlock.js
  src/casus/blocks/IntGreaterThanOrEqualBlock.js
  src/casus/blocks/IntLessThanBlock.js
  src/casus/blocks/IntLessThanOrEqualBlock.js
  src/casus/blocks/IntMaxBlock.js
  src/casus/blocks/IntMinBlock.js
  src/casus/blocks/IntModuloBlock.js
  src/casus/blocks/IntMultiplyBlock.js
  src/casus/blocks/IntSubtractBlock.js
  src/casus/blocks/IntToDoubleBlock.js
  src/casus/blocks/ListAppendBlock.js
  src/casus/blocks/ListSizeBlock.js
  src/casus/blocks/MathAcosBlock.js
  src/casus/blocks/MathAsinBlock.js
  src/casus/blocks/MathAtanBlock.js
  src/casus/blocks/MathCosBlock.js
  src/casus/blocks/MathPowBlock.js
  src/casus/blocks/MathSqrtBlock.js
  src/casus/blocks/MathTanBlock.js
  src/casus/blocks/NotBlock.js
  src/casus/blocks/OrBlock.js
  src/casus/blocks/PrintBlock.js
  src/casus/blocks/SetListAtBlock.js
  src/casus/blocks/SetVariableBlock.js
  src/casus/blocks/WhileBlock.js
  src/casus/blocks/XorBlock.js
  src/casus/interpreter/InterpriterState.js
  src/tanks/Tank.js
Labels: casus, front-end

#393 Toast implemented
  src/armory/Armory.css
  src/armory/Armory.js
  src/armory/CreateNewTankPopup.js
  src/armory/DeleteTankPopup.js
  src/armory/RenameTankPopup.js
  src/armory/SetWagerPopup.js
  src/globalComponents/apiCalls/getAllUsersAPICall.js
  src/globalComponents/apiCalls/getBotTanksAPICall.js
  src/globalComponents/apiCalls/getMatchAPICall.js
  src/globalComponents/apiCalls/getReplayListAPICall.js
  src/globalComponents/apiCalls/getUserAPICall.js
  src/globalComponents/apiCalls/prepareMatchAPICall.js
  src/globalComponents/apiCalls/reportMatchResultAPICall.js
  src/globalComponents/apiCalls/tankAPIIntegration.js
  src/globalComponents/apiCalls/userAPIIntegration.js
  src/globalComponents/apiCalls/verifyLogin.js
  src/login/LoginPopup.js
  src/login/ResendEmailPopup.js
  src/login/SignupPopup.js
Labels: bug, front-end

#394 implemented new elo library for ties
  package.json
  src/backend/controllers/battleController.js
  src/backend/routes/battleRoutes.js
Labels: api

#400 Data layer testing
  src/models/battleRecordModel.test.js
  src/models/marketSaleModel.test.js
  src/models/tankModel.test.js
  src/models/tokenModel.js
  src/models/tokenModel.test.js
  src/models/userModel.test.js
Labels: back-end, testing

#409 Made view button smaller, change replay status, and added name color
  src/Main.css
  src/battlearena/BattleArena.css
  src/battlearena/Replays.js
Labels: bug

#408 Updates to daily wager stipend and implemented first win of day streaks.
  src/backend/controllers/battleController.js
  src/backend/controllers/userController.js
  src/models/userModel.js
Labels: api

#413 Made map property in BattleRecord
  src/models/battleRecordModel.js
Labels: back-end

#406 Refactored API calls to reduce code
  src/armory/Armory.js
  src/armory/CreateNewTankPopup.js
  src/armory/DeleteTankPopup.js
  src/armory/RenameTankPopup.js
  src/armory/SetWagerPopup.js
  src/backend/controllers/tankController.js
  src/battlearena/BattleArena.js
  src/battlearena/ChallengePlayerPopup.js
  src/battlearena/SearchPlayers.js
  src/battleground/getTanksToFightOnBattleground.js
  src/casus/CasusContainer.js
  src/globalComponents/GetInventoryInfo.js
  src/globalComponents/apiCalls/getAllUsersAPICall.js
  src/globalComponents/apiCalls/getBotTanksAPICall.js
  src/globalComponents/apiCalls/getMatchAPICall.js
  src/globalComponents/apiCalls/getReplayListAPICall.js
  src/globalComponents/apiCalls/getUserAPICall.js
  src/globalComponents/apiCalls/marketPlaceAPIConnections.js
  src/globalComponents/apiCalls/prepareMatchAPICall.js
  src/globalComponents/apiCalls/reportMatchResultAPICall.js
  src/globalComponents/apiCalls/tankAPIIntegration.js
  src/globalComponents/apiCalls/userAPIIntegration.js
  src/globalComponents/typesAndClasses/SaleObject.js
  src/globalComponents/typesAndClasses/User.js
  src/marketplace/ListingObject.js
  src/marketplace/ListingsView.js
  src/marketplace/MakeAComponentSaleView.js
  src/marketplace/MakeATankSaleView.js
  src/marketplace/marketPlaceAPIConnections.js
  src/trainingarena/TrainingArena.js
Labels: front-end

#418 Updated unfavoriteTank API to handle setting wager to 0
  src/armory/SetWagerPopup.js
  src/backend/controllers/tankController.js
  src/backend/routes/tankRoutes.js
Labels: api

#419 3v3 favorites APIs
  src/backend/controllers/tankController.js
  src/backend/routes/tankRoutes.js
Labels: api

#416 Prepare 3v3 match api
  src/backend/controllers/battleController.js
  src/backend/routes/battleRoutes.js
  src/models/battleRecordModel.js
Labels: api

#427 Toast messages for dailys
  src/armory/SetWagerPopup.js
  src/backend/controllers/battleController.js
  src/backend/controllers/tankController.js
  src/backend/controllers/userController.js
  src/battlearena/Replays.js
  src/battleground/Battleground.js
  src/globalComponents/apiCalls/reportMatchResultAPICall.js
  src/globalComponents/apiCalls/userAPIIntegration.js
Labels: api, front-end

#440 Frontend 3v3 handling 1/2
  src/armory/Armory.css
  src/armory/Armory.js
  src/backend/controllers/battleController.js
  src/battlearena/BattleArena.css
  src/battlearena/BattleArena.js
  src/globalComponents/SelectTank.js
  src/globalComponents/apiCalls/prepareMatchAPICall.js
  src/globalComponents/typesAndClasses/BattleType.js
  src/tanks/TankDisplay.css
  src/tanks/TankDisplay.js
  src/trainingarena/TrainingArena.css
  src/trainingarena/TrainingArena.js
Labels: api, front-end

#441 Get tank api
  src/backend/controllers/tankController.js
  src/backend/routes/tankRoutes.js
  src/models/userModel.js
Labels: api

#433 Made name sizes scale down when they are too big
  src/battleground/HealthBar.js
Labels: front-end

#439 Maintain selected tank and arena
  src/armory/Armory.js
  src/battlearena/BattleArena.js
  src/globalComponents/SelectTank.js
  src/globalComponents/getPreferredArena.js
  src/globalComponents/getPreferredSelectedTank.js
  src/globalComponents/setPreferredArena.js
  src/globalComponents/setPreferredSelectedTank.js
  src/trainingarena/TrainingArena.js
Labels: front-end

#445 Duplicate items cannot be equipped (except mines)
  src/armory/Armory.js
Labels: front-end

#448 Replay table now shows more information
  src/battlearena/BattleArena.css
  src/battlearena/Replays.js
  src/globalComponents/apiCalls/getReplayListAPICall.js
  src/globalComponents/typesAndClasses/Replay.js
Labels: front-end

#450 Reset password functionality
  src/Main.css
  src/backend/controllers/userController.js
  src/backend/routes/userRoutes.js
  src/index.js
  src/login/LoginPopup.js
  src/login/ResetPassword.js
  src/models/tokenModel.js
Labels: api, back-end, front-end

#422 Remove Active Sales and Link to youtube
  src/Main.css
  src/backend/controllers/marketController.js
  src/backend/routes/marketRoutes.js
  src/globalComponents/Navbar.js
  src/globalComponents/YoutubeVideoPopup.js
  src/globalComponents/apiCalls/marketPlaceAPIConnections.js
  src/marketplace/Marketplace.js
  src/marketplace/MarketplaceViewDataTypes.js
  src/marketplace/RemoveASaleView.js
Labels: api, front-end

#447 Show tank components being sold
  src/globalComponents/apiCalls/marketPlaceAPIConnections.js
  src/globalComponents/apiCalls/tankAPIIntegration.js
  src/globalComponents/typesAndClasses/SaleObject.js
  src/marketplace/ListingsView.js
  src/marketplace/ShowTankPopup.js
Labels: front-end

#452 Armory tutorial and navbar help update
  src/Main.css
  src/armory/Armory.js
  src/globalComponents/Navbar.js
  src/globalComponents/YoutubeVideoPopup.js
  src/marketplace/Marketplace.js
Labels: front-end

#454 3v3wagerinmodel
  src/backend/controllers/battleController.js
  src/models/userModel.js
Labels: back-end

#455 Fix broken weapons (Pulse Laser and Lancer)
  src/battleground/Battleground.js
  src/battleground/gameobjects/Bullet.js
Labels: front-end, game

#461 I'm an idiot.
  src/backend/controllers/userController.js
Labels: api

#459 Added youtube video link to BattleArena
  src/battlearena/BattleArena.js
Labels: front-end

#463 Set 3v3 wager now works on front and back end
  src/Main.css
  src/armory/Armory.css
  src/armory/Armory.js
  src/armory/SetWagerPopup.js
  src/backend/controllers/tankController.js
  src/backend/controllers/userController.js
  src/backend/routes/tankRoutes.js
  src/backend/routes/userRoutes.js
  src/battlearena/ChallengePlayerPopup.js
  src/globalComponents/YoutubeVideoPopup.js
  src/globalComponents/apiCalls/getAllUsersAPICall.js
  src/globalComponents/apiCalls/getUserAPICall.js
  src/globalComponents/apiCalls/tankAPIIntegration.js
  src/globalComponents/apiCalls/userAPIIntegration.js
  src/globalComponents/typesAndClasses/User.js
Labels: api, front-end

#462 added trainingArenaTutorial
  src/trainingarena/TrainingArena.js
Labels: sd tasks

#466 Battle Arena now allows users to correctly challenge each other for 3v3s
  src/backend/controllers/battleController.js
  src/backend/controllers/tankController.js
  src/backend/routes/battleRoutes.js
  src/battlearena/BattleArena.js
  src/battlearena/ChallengePlayerPopup.js
  src/battlearena/SearchPlayers.js
  src/battleground/Battleground.js
  src/battleground/getTanksToFightOnBattleground.js
  src/globalComponents/apiCalls/getMatchAPICall.js
  src/globalComponents/apiCalls/prepareMatchAPICall.js
  src/tanks/Gun.js
  src/tanks/TankLoader.js
Labels: api, front-end

#446 Unverified users get removed in 1 day and tank creation now in login.
  src/backend/controllers/userController.js
  src/models/userModel.js
Labels: api, back-end

#480 Removed crash when switching from component to tank view
  src/marketplace/ListingsView.js
Labels: bug

#481 Design updates
  src/Main.css
  src/backend/controllers/userController.js
  src/globalComponents/SelectTank.js
  src/login/ConfirmEmail.js
  src/login/InfoPopup.js
  src/login/Login.css
  src/mainmenu/MainMenu.css
  src/mainmenu/MainMenu.js
  src/marketplace/ListingsView.js
  src/marketplace/MakeAComponentSaleView.js
  src/trainingarena/TrainingArena.js
Labels: front-end

#505 Fixed username/password checking
  src/backend/controllers/userController.js
Labels: api

#508 Updated the Listings to handle when the sellerId is Master's Id
  src/marketplace/ListingsView.js
  src/marketplace/Marketplace.css
Labels: front-end

#509 Added undo button in Casus that is in a fixed position
  src/casus/CasusEditor.css
  src/casus/CasusEditor.js
  src/casus/blockBank/BlockBank.css
  src/casus/casusBlockDeepClone.js
Labels: front-end

#514 Removed infinite get users calls in Battle Arena
  src/battlearena/SearchPlayers.js
Labels: bug, front-end

#518 added logic to sell tank code libraries.
  src/backend/controllers/marketController.js
Labels: api

#521 updated battleRecordModel test due to model update.
  src/models/battleRecordModel.test.js
Labels: testing

#522 Fixed removing sales to correctly move last sale
  src/globalComponents/apiCalls/marketPlaceAPIConnections.js
  src/marketplace/RemoveASaleView.js
Labels: bug, front-end

#519 No more API calls when switching listings
  src/casus/CasusEditor.css
  src/globalComponents/typesAndClasses/MarketplaceViewType.js
  src/globalComponents/typesAndClasses/SellingType.js
  src/marketplace/ListingsView.js
  src/marketplace/MakeAComponentSaleView.js
  src/marketplace/Marketplace.js
  src/marketplace/MarketplaceViewDataTypes.js
  src/marketplace/SellingType.js
Labels: bug, front-end

#526 Added validation for item price and amount
  src/backend/routes/marketRoutes.js
Labels: api, bug

#530 Edited Environment Variable Access for Master account
  src/backend/controllers/marketController.js
  src/backend/controllers/userController.js
  src/globalComponents/getMasterAccountId.js
Labels: api, front-end

#532 First tank found is now initial selling tank in MakeATankSaleView
  src/marketplace/MakeATankSaleView.js
Labels: bug, front-end

#534 3v3 Wagers now set correctly
  src/armory/SetWagerPopup.js
  src/backend/controllers/tankController.js
  src/globalComponents/apiCalls/tankAPIIntegration.js
Labels: bug, front-end

#536 Wagers now uses SelectTank.js
  src/armory/Armory.js
  src/armory/SetWagerPopup.js
  src/battlearena/BattleArena.js
  src/globalComponents/SelectTank.js
  src/trainingarena/TrainingArena.js
Labels: bug, front-end
