Repository RickLeinecker/Fortuna, pull requests merged in 2020-03, with the labels that each got.

#114 Email Confirmation Implemented
  .gitignore
  package.json
  src/backend/controllers/userController.js
  src/backend/routes/casusRoutes.js
  src/backend/routes/userRoutes.js
  src/backend/server.js
  src/models/tokenModel.js
  src/models/userModel.js
Labels: api, back-end

#116 Marketplace API implementation
  src/backend/controllers/marketController.js
  src/backend/routes/marketRoutes.js
  src/backend/server.js
  src/models/marketSaleModel.js
  src/models/userModel.js
Labels: api, back-end

#120 TANKS RUN CODE AND MOVE!
  assets/art/backgrounds/Wall.kra
  assets/art/backgrounds/Wall.kra~
  assets/art/backgrounds/Wall.png
  public/Wall.png
  src/battleground/Battleground.js
  src/battleground/ImageDrawer.js
  src/battleground/ImageLoader.js
  src/battleground/ImageName.js
  src/battleground/Wall.js
  src/battleground/getBattlegroundHeight.js
  src/battleground/getBattlegroundWidth.js
  src/casus/blocks/GetVariableBlock.js
  src/casus/blocks/Vec.js
  src/casus/interpreter/InterpriterState.js
  src/casus/userInteraction/defaultVariableNames.js
  src/tanks/Chassis.js
  src/tanks/Gun.js
  src/tanks/Tank.js
  src/tanks/TankLoader.js
  src/tanks/TankPart.js
  src/tanks/Treads.js
Labels: casus, front-end

#121 Search players and its CSS and BattleArena changes integrated.
  src/Main.css
  src/battlearena/BattleArena.js
  src/battlearena/SearchPlayers.js
Labels: front-end

#119 Updated/Added Models to reflect CDR
  src/models/battleRecordModel.js
  src/models/tankModel.js
  src/models/userModel.js
Labels: back-end

#127 Cleaned up all frontend files excluding Casus
  src/Main.css
  src/RoutePathType.js
  src/armory/Armory.js
  src/battlearena/BattleArena.js
  src/battlearena/SearchPlayers.js
  src/globalComponents/Leaderboard.js
  src/globalComponents/Navbar.js
  src/login/InfoPopup.js
  src/login/Login.js
  src/login/LoginPopup.js
  src/login/SignupPopup.js
  src/mainmenu/MainMenu.js
  src/marketplace/Marketplace.js
  src/trainingarena/TrainingArena.js
Labels: front-end

#132 Replay API Implementation
  package.json
  src/backend/controllers/replayController.js
  src/backend/routes/replayRoutes.js
  src/backend/routes/userRoutes.js
  src/backend/server.js
  src/models/battleRecordModel.js
Labels: api, back-end

#131 Finished Armory
  debug.log
  package.json
  src/armory/Armory.js
  src/armory/ComponentType.js
  src/armory/GetInventoryInfo.js
  src/backend/controllers/casusController.js
  src/backend/controllers/tankController.js
  src/backend/controllers/userController.js
  src/backend/routes/casusRoutes.js
  src/backend/routes/tankRoutes.js
  src/backend/routes/userRoutes.js
  src/backend/server.js
  src/login/LoginPopup.js
Labels: api, front-end

#137 Split up and Fixed CSS
  src/Main.css
  src/armory/Armory.css
  src/armory/Armory.js
  src/battlearena/BattleArena.css
  src/battlearena/BattleArena.js
  src/globalComponents/Leaderboard.js
  src/login/InfoPopup.js
  src/login/Login.css
  src/login/Login.js
  src/login/LoginPopup.js
  src/login/SignupPopup.js
  src/mainmenu/MainMenu.css
  src/mainmenu/MainMenu.js
  src/marketplace/Marketplace.js
  src/trainingarena/TrainingArena.css
  src/trainingarena/TrainingArena.js
Labels: front-end

#138 Added Challenge player functionality
  src/Main.css
  src/battlearena/BattleArena.js
  src/battlearena/ChallengePlayerPopup.js
  src/battlearena/SearchPlayers.js
  src/globalComponents/SelectTank.js
Labels: front-end

#151 Navbar fixes.
  src/Main.css
  src/globalComponents/Navbar.js
Labels: front-end

#158 Marketplace Component Part Done
  src/armory/Armory.js
  src/marketplace/AccessoriesView.js
  src/marketplace/CannonsView.js
  src/marketplace/CasusBlocksView.js
  src/marketplace/ChassisView.js
  src/marketplace/JammersView.js
  src/marketplace/ListingsView.js
  src/marketplace/MakeAComponentSaleView.js
  src/marketplace/Marketplace.js
  src/marketplace/MarketplaceViewDataTypes.js
  src/marketplace/ScannersView.js
  src/marketplace/TreadsView.js
Labels: api, back-end, front-end

#168 Bugfix/email production fix
  package.json
  src/backend/controllers/userController.js
Labels: api, back-end

#167 Bugfix/marketplace fixes
  package.json
  src/backend/controllers/marketController.js
  src/backend/routes/marketRoutes.js
  src/marketplace/ListingsView.js
Labels: api, back-end, front-end

#192 Logout and quick login implemented.
  src/globalComponents/Navbar.js
  src/login/Login.js
  src/mainmenu/MainMenu.js
Labels: front-end

#194 Created Mines and C4
  assets/art/deployables/c4.kra
  assets/art/deployables/mine.kra
  assets/art/deployables/mineUntriggered.kra
  assets/art/particles/Ember1.kra
  assets/art/particles/Ember2.kra
  assets/art/particles/Smoke1.kra
  assets/art/particles/Smoke2.kra
  assets/art/particles/Smoke2.png~
  assets/art/particles/smoke3.kra
  public/Ember1.png
  public/Ember2.png
  public/Smoke1.png
  public/Smoke2.png
  public/c4.png
  public/mine.png
  public/mineUntriggered.png
  public/smoke3.png
  src/battleground/Battleground.js
  src/battleground/GameObject.js
  src/battleground/ImageDrawer.js
  src/battleground/ImageLoader.js
  src/battleground/ImageName.js
  src/battleground/Wall.js
  src/battleground/gameobjects/C4.js
  src/battleground/gameobjects/Mine.js
  src/battleground/gameobjects/Particle.js
  src/tanks/Tank.js
Labels: front-end

#208 Scanners and player positions
  assets/art/particles/Electricity.kra
  assets/art/particles/ElectricityFlipped.kra
  assets/art/particles/ElectricityFlipped.kra~
  assets/art/particles/EmpPulse.kra
  assets/art/particles/EmpPulse.kra~
  assets/art/particles/static.kra
  assets/art/particles/static.kra~
  assets/art/scannersAndJammers/AntiJammerBubble.kra
  assets/art/scannersAndJammers/JammerLarge.kra
  assets/art/scannersAndJammers/JammerLarge.kra~
  assets/art/scannersAndJammers/JammerMedium.kra
  assets/art/scannersAndJammers/JammerMedium.kra~
  assets/art/scannersAndJammers/JammerSmall.kra
  assets/art/scannersAndJammers/JammerSmall.kra~
  assets/art/scannersAndJammers/LargeItemsScanner.kra
  assets/art/scannersAndJammers/MediumItemsScanner.kra
  assets/art/scannersAndJammers/MediumScanner.kra
  assets/art/scannersAndJammers/scannerItemsSmall.kra
  assets/art/scannersAndJammers/scannerSmall.kra
  public/AntiJammerBubble.png
  public/Electricity.png
  public/ElectricityFlipped.png
  public/EmpPulse.png
  public/JammerLarge.png
  public/JammerMedium.png
  public/JammerSmall.png
  public/LargeItemsScanner.png
  public/LargeScanner.png
  public/MediumItemsScanner.png
  public/MediumScanner.png
  public/scannerItemsSmall.png
  public/scannerSmall.png
  public/static.png
  src/battleground/Battleground.js
  src/battleground/GameObject.js
  src/battleground/ImageDrawer.js
  src/battleground/ImageLoader.js
  src/battleground/ImageName.js
  src/battleground/Wall.js
  src/battleground/gameobjects/C4.js
  src/battleground/gameobjects/Mine.js
  src/battleground/gameobjects/Particle.js
  src/casus/interpreter/BooleanListValue.js
  src/casus/interpreter/DoubleListValue.js
  src/casus/interpreter/IntListValue.js
  src/casus/userInteraction/CasusSpecialVariables.js
  src/casus/userInteraction/SelectVariablePopup.js
  src/tanks/Jammer.js
  src/tanks/Scanner.js
  src/tanks/Tank.js
  src/tanks/TankLoader.js
  src/tanks/TankPart.js
Labels: casus, game

#212 Cleaned up ConfirmEmail and added a link to login
  src/login/ConfirmEmail.js
  src/login/Login.css
Labels: front-end

#211 Casus look and navigation updated
  src/Main.css
  src/casus/CasusContainer.css
  src/casus/CasusContainer.js
  src/casus/CasusEditor.js
  src/casus/blockBank/BlockBankBlockShelf.js
  src/casus/blockBank/BlockBankTypeSelector.css
  src/casus/blockBank/BlockBankTypeSelector.js
  src/casus/blocks/BinaryOperationBlock.js
  src/casus/blocks/CasusBlock.js
  src/casus/blocks/ContainerBlock.js
  src/casus/blocks/EmptyBlock.js
  src/casus/blocks/ForBlock.js
  src/casus/blocks/GetListAtBlock.js
  src/casus/blocks/GetVariableBlock.js
  src/casus/blocks/IfElseBlock.js
  src/casus/blocks/ListSizeBlock.js
  src/casus/blocks/SetListAtBlock.js
  src/casus/blocks/SetVariableBlock.js
  src/casus/blocks/SingleConditionHeader.js
  src/casus/blocks/UnaryOperationBlock.js
  src/casus/userInteraction/SelectVariablePopup.css
  src/casus/userInteraction/SelectVariablePopup.js
  src/trainingarena/TrainingArena.css
  src/trainingarena/TrainingArena.js
Labels: front-end

#223 Api runthrough
  src/backend/controllers/casusController.js
  src/backend/controllers/marketController.js
  src/backend/controllers/replayController.js
  src/backend/controllers/tankController.js
  src/backend/controllers/userController.js
  src/backend/routes/casusRoutes.js
  src/backend/routes/marketRoutes.js
  src/backend/routes/replayRoutes.js
  src/backend/routes/tankRoutes.js
  src/backend/routes/userRoutes.js
Labels: api

#235 Implemented API to Delete Tanks
  src/backend/controllers/tankController.js
  src/backend/routes/tankRoutes.js
Labels: api

#236 Updated logic for deleteTanks per post merge comments
  src/backend/controllers/tankController.js
Labels: api

#232 Created Separate getTankMarketSales route to get tanks and enable getting their names
  src/backend/controllers/marketController.js
  src/backend/routes/marketRoutes.js
  src/models/marketSaleModel.js
Labels: api, back-end

#231 Api jwt verification
  src/backend/controllers/tankController.js
  src/backend/controllers/userController.js
  src/backend/controllers/verifyController.js
  src/backend/middleware/auth.js
  src/backend/routes/tankRoutes.js
  src/backend/routes/userRoutes.js
  src/backend/routes/verifyRoute.js
  src/backend/server.js
Labels: api

#226 Armory change, selected tank cookie, and more.
  src/Main.css
  src/armory/Armory.css
  src/armory/Armory.js
  src/armory/Component.js
  src/armory/ComponentType.js
  src/armory/CreateNewTankPopup.js
  src/armory/GetInventoryInfo.js
  src/armory/OptionClass.js
  src/armory/TankComponent.js
  src/backend/routes/tankRoutes.js
  src/battleground/Battleground.js
  src/globalComponents/setTankForCasus.js
  src/marketplace/ListingsView.js
  src/tanks/BackendTank.js
  src/tanks/Chassis.js
  src/tanks/Gun.js
  src/tanks/Jammer.js
  src/tanks/Range.js
  src/tanks/Scanner.js
  src/tanks/Tank.js
  src/tanks/TankLoader.js
  src/tanks/TankPart.js
  src/tanks/Treads.js
Labels: front-end

#247 New tanks for newbs
  src/backend/controllers/userController.js
Labels: api

#193 index.js now checks if a user is logged in before rendering a page
  src/App.js
  src/armory/Armory.js
  src/backend/controllers/verifyController.js
  src/battlearena/BattleArena.js
  src/battleground/Battleground.js
  src/casus/CasusContainer.js
  src/globalComponents/LinkType.js
  src/globalComponents/Navbar.js
  src/globalComponents/verifyLink.js
  src/globalComponents/verifyLogin.js
  src/index.js
  src/login/Login.js
  src/login/LoginPopup.js
  src/mainmenu/MainMenu.js
  src/marketplace/Marketplace.js
  src/trainingarena/TrainingArena.js
Labels: bug, front-end

#248 Updated logic for updating inventory on tank edit.
  src/backend/controllers/tankController.js
  src/models/tankModel.js
Labels: api, back-end

#255 Made HTML email body for emails. Also have alternative text bodies.
  src/backend/controllers/userController.js
Labels: api

#249 Point tracking
  src/Main.css
  src/armory/Armory.css
  src/armory/Armory.js
  src/armory/Component.js
  src/armory/GetInventoryInfo.js
  src/backend/controllers/tankController.js
Labels: front-end

#259 Finished post-game scene and game timer, minus API call
  src/battleground/Battleground.js
  src/battleground/ImageDrawer.js
  src/battleground/gameobjects/Bullet.js
  src/battleground/gameobjects/C4.js
  src/battleground/gameobjects/Mine.js
  src/casus/interpreter/DoubleValue.js
  src/tanks/Chassis.js
  src/tanks/Tank.js
  src/tanks/TankLoader.js
  src/tanks/Treads.js
Labels: front-end, game

#261 CreateTankPopup fully functional
  src/Main.css
  src/armory/Armory.css
  src/armory/Armory.js
  src/armory/CreateNewTankPopup.js
  src/armory/SelectTank.js
  src/backend/controllers/tankController.js
Labels: front-end

#258 Api battles
  package.json
  src/backend/controllers/battleController.js
  src/backend/controllers/userController.js
  src/backend/routes/battleRoutes.js
  src/backend/routes/userRoutes.js
  src/backend/server.js
Labels: api, back-end

#267 Added wagerUpdate and default money to user
  src/models/userModel.js
Labels: back-end

#272 Removed setState in constructors
  src/armory/Armory.js
  src/armory/CreateNewTankPopup.js
  src/globalComponents/Navbar.js
Labels: bug

#225 Buying and selling tanks
  src/armory/Armory.js
  src/backend/controllers/marketController.js
  src/globalComponents/Utility.js
  src/globalComponents/tankAPIIntegration.js
  src/marketplace/ListingsView.js
  src/marketplace/MakeATankSaleView.js
  src/marketplace/Marketplace.js
  src/marketplace/MarketplaceViewDataTypes.js
  src/marketplace/SaleObject.js
  src/marketplace/SellingType.js
  src/marketplace/marketPlaceAPIConnections.js
Labels: front-end

#273 Master component listings on marketplace
  src/backend/controllers/marketController.js
  src/backend/controllers/userController.js
Labels: api

#270 Empty option for component menu and DeleteTankPopup
  src/armory/Armory.css
  src/armory/Armory.js
  src/armory/CreateNewTankPopup.js
  src/armory/DeleteTankPopup.js
Labels: front-end

#260 Health bar
  .flowconfig
  src/Main.css
  src/battleground/Battleground.js
  src/battleground/BattlegroundContainer.js
  src/battleground/HealthBar.js
  src/battleground/HealthBarsField.js
  src/index.js
  src/tanks/Tank.js
Labels: front-end, game

#283 Update default cases for wagerDate and favoriteTank
  src/models/userModel.js
Labels: back-end

#268 Added rendering of tank in armory
  assets/art/backgrounds/Shadow.kra
  assets/art/backgrounds/Shadow.kra~
  assets/art/tankChassis/Chassis4.kra
  public/Chassis4.png
  public/Shadow.png
  src/armory/Armory.js
  src/battleground/Battleground.js
  src/battleground/ImageDrawer.js
  src/battleground/ImageLoader.js
  src/battleground/ImageName.js
  src/tanks/Chassis.js
  src/tanks/Tank.js
  src/tanks/TankDisplay.css
  src/tanks/TankDisplay.js
  src/tanks/Treads.js
Labels: front-end

#297 Added logic to prevent deletion of final tank.
  src/backend/controllers/marketController.js
  src/backend/controllers/tankController.js
Labels: api

#308 SetWagerPopup implemented and cleaned up armory.
  src/armory/Armory.css
  src/armory/Armory.js
  src/armory/CreateNewTankPopup.js
  src/armory/DeleteTankPopup.js
  src/armory/SetWagerPopup.js
  src/globalComponents/User.js
  src/globalComponents/getUserAPICall.js
  src/globalComponents/tankAPIIntegration.js
  src/globalComponents/userAPIIntegration.js
  src/marketplace/MakeATankSaleView.js
  src/tanks/BackendTank.js
Labels: front-end

#241 Toasty
  package.json
  src/marketplace/ListingsView.js
  src/marketplace/MakeAComponentSaleView.js
  src/marketplace/MakeATankSaleView.js
Labels: front-end

#310 RenameTankPopup fully implemented.
  src/armory/Armory.js
  src/armory/CreateNewTankPopup.js
  src/armory/RenameTankPopup.js
  src/armory/SetWagerPopup.js
  src/globalComponents/tankAPIIntegration.js
Labels: front-end

#305 CSS issue fixes.
  src/armory/Armory.js
  src/login/Login.css
Labels: bug, front-end

#313 Get bot tanks
  src/backend/controllers/tankController.js
  src/backend/routes/tankRoutes.js
Labels: api

#324 Update tank display when new scanner selected
  src/armory/Armory.js
Labels: front-end

#328 Renaming favorite tank also updates the wager
  src/armory/Armory.js
  src/armory/SetWagerPopup.js
Labels: bug, front-end

#325 Leaderboard now displays ELO
  src/Main.css
  src/battlearena/BattleArena.css
  src/globalComponents/Leaderboard.js
  src/globalComponents/User.js
  src/globalComponents/getUserAPICall.js
  src/globalComponents/userAPIIntegration.js
  src/login/Login.css
Labels: front-end

#330 Fixed incorrect references for SetWagerPopup
  src/armory/SetWagerPopup.js
Labels: bug, front-end

#323 Centered battleground and made it higher definition
  src/battleground/Battleground.css
  src/battleground/Battleground.js
  src/battleground/BattlegroundContainer.css
  src/battleground/BattlegroundContainer.js
  src/battleground/HealthBar.css
  src/battleground/HealthBar.js
  src/battleground/getBattlegroundWidth.js
Labels: front-end, game

#334 Fixed table error
  src/globalComponents/Leaderboard.js
Labels: bug, front-end

#338 Added getMatch API
  src/backend/controllers/battleController.js
  src/backend/routes/battleRoutes.js
Labels: api

#340 Quickplay now searches for a player in similar elo (that is not you).
  src/battlearena/BattleArena.css
  src/battlearena/BattleArena.js
  src/battlearena/ChallengePlayerPopup.js
Labels: bug, front-end

#343 updated default value for casusCode for tank model
  src/models/tankModel.js
Labels: back-end

#326 Added Edit/Delete User API routes
  src/backend/controllers/userController.js
  src/backend/routes/userRoutes.js
Labels: api

#344 Show list of past matches
  src/backend/controllers/replayController.js
  src/backend/routes/replayRoutes.js
  src/battlearena/BattleArena.css
  src/battlearena/BattleArena.js
  src/battlearena/ChallengePlayerPopup.js
  src/battlearena/Replays.js
  src/battlearena/SearchPlayers.js
  src/globalComponents/Leaderboard.js
  src/globalComponents/Replay.js
  src/globalComponents/getReplayListAPICall.js
Labels: front-end
