Repository RickLeinecker/Fortuna, pull requests merged in 2020-01, with the labels that each got.

#46 Casus Block Bank creation
  fortuna/src/casus/BlockBank.js
  fortuna/src/casus/CasusContainer.css
  fortuna/src/casus/CasusContainer.js
  fortuna/src/casus/CasusEditor.css
  fortuna/src/casus/CasusEditor.js
  fortuna/src/casus/blockBank/BlockBank.css
  fortuna/src/casus/blockBank/BlockBank.js
  fortuna/src/casus/blockBank/BlockBankBlockShelf.css
  fortuna/src/casus/blockBank/BlockBankBlockShelf.js
  fortuna/src/casus/blockBank/BlockBankType.js
  fortuna/src/casus/blockBank/BlockBankTypeSelector.css
  fortuna/src/casus/blockBank/BlockBankTypeSelector.js
  fortuna/src/casus/blocks/ContainerBlock.js
  fortuna/src/login/Login.js
Labels: casus

#47 Casus Drag and Drop
  fortuna/.babelrc
  fortuna/src/casus/CasusContainer.js
  fortuna/src/casus/CasusEditor.js
  fortuna/src/casus/blockBank/BlockBank.js
  fortuna/src/casus/blockBank/BlockBankBlockShelf.js
  fortuna/src/casus/blocks/AndBlock.js
  fortuna/src/casus/blocks/BinaryOperationBlock.js
  fortuna/src/casus/blocks/CasusBlock.js
  fortuna/src/casus/blocks/ContainerBlock.js
  fortuna/src/casus/blocks/EmptyBlock.js
  fortuna/src/casus/blocks/ForBlock.js
  fortuna/src/casus/blocks/SetVariableBlock.js
  fortuna/src/casus/blocks/VariableBlock.js
  fortuna/src/casus/blocks/generateCornerPerim.js
Labels: casus, front-end

#48 If Block, If-else Block, and While Block for Casus
  fortuna/src/casus/CasusEditor.js
  fortuna/src/casus/blockBank/BlockBankBlockShelf.js
  fortuna/src/casus/blocks/BinaryOperationBlock.js
  fortuna/src/casus/blocks/CasusBlock.js
  fortuna/src/casus/blocks/ContainerBlock.js
  fortuna/src/casus/blocks/ForBlock.js
  fortuna/src/casus/blocks/IfBlock.js
  fortuna/src/casus/blocks/IfElseBlock.js
  fortuna/src/casus/blocks/SetVariableBlock.js
  fortuna/src/casus/blocks/SingleConditionHeader.js
  fortuna/src/casus/blocks/WhileBlock.js
  fortuna/src/casus/blocks/generateCornerPerim.js
Labels: casus

#51 Jorge
  fortuna/src/BattleArena/BattleArena.css
  fortuna/src/BattleArena/BattleArena.js
  fortuna/src/index.js
  fortuna/src/mainmenu/MainMenu.js
Labels: front-end

#54 Added Casus Inventory field to user model.
  fortuna/src/models/userModel.js
Labels: back-end

#57 CSS Changes
  fortuna/src/Main.css
  fortuna/src/login/InfoPopup.js
  fortuna/src/login/Login.css
  fortuna/src/login/Login.js
  fortuna/src/login/LoginPopup.js
  fortuna/src/login/SignupPopup.js
Labels: front-end

#62 Fine Tuned Login UI and added Navbar and Leaderboard
  src/Main.css
  src/login/InfoPopup.js
  src/login/Leaderboard.js
  src/login/Login.css
  src/login/Login.js
  src/login/LoginPopup.js
  src/login/Navbar.js
  src/login/SignupPopup.js
Labels: documentation, front-end

#71 Created all List blocks and popups to create variables
  src/casus/CasusContainer.css
  src/casus/CasusEditor.js
  src/casus/blockBank/BlockBankBlockShelf.js
  src/casus/blockBank/BlockBankTypeSelector.css
  src/casus/blocks/DataType.js
  src/casus/blocks/GetListAtBlock.js
  src/casus/blocks/GetVariableBlock.js
  src/casus/blocks/ListSizeBlock.js
  src/casus/blocks/SetListAtBlock.js
  src/casus/blocks/SetVariableBlock.js
  src/casus/blocks/generateCornerPerim.js
  src/casus/blocks/measureText.js
  src/casus/userInteraction/SelectVariablePopup.css
  src/casus/userInteraction/SelectVariablePopup.js
  src/casus/userInteraction/defaultVariableNames.js
Labels: casus

#65 Update to API/Routes Design Pattern, Adding Login/Signup API, Tank API **Be sure to title your PRs next time :)**
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/pull_request_template.md
  package.json
  src/backend/controllers/tankController.js
  src/backend/controllers/userController.js
  src/backend/middleware/auth.js
  src/backend/routes/api/home.js
  src/backend/routes/api/signup.js
  src/backend/routes/tankRoutes.js
  src/backend/routes/userRoutes.js
  src/backend/server.js
  src/login/Login.css
Labels: api, back-end

#75 Clarified lines and added verification steps section for PR template
  .github/pull_request_template.md
Labels: workflow

#68 2 New Components and CSS Architecture Fix
  src/BattleArena/BattleArena.css
  src/BattleArena/BattleArena.js
  src/Main.css
  src/armory/Armory.js
  src/components/Leaderboard.js
  src/components/LinkType.js
  src/components/Navbar.js
  src/index.js
  src/login/InfoPopup.js
  src/login/Leaderboard.js
  src/login/Login.css
  src/login/Login.js
  src/login/LoginPopup.js
  src/login/Navbar.js
  src/login/SignupPopup.js
  src/mainmenu/MainMenu.css
  src/mainmenu/MainMenu.js
Labels: bug, documentation, front-end
