Repository RickLeinecker/Fortuna, pull requests merged in 2020-02, with the labels that each got.

#87 Training Arena and Armory
  src/BattleArena/BattleArena.js
  src/Main.css
  src/RoutePathType.js
  src/armory/Armory.js
  src/battlearena/BattleArena.js
  src/components/Navbar.js
  src/index.js
  src/login/InfoPopup.js
  src/login/Login.js
  src/login/LoginPopup.js
  src/login/SignupPopup.js
  src/mainmenu/MainMenu.js
  src/trainingarena/TrainingArena.js
Labels: bug, front-end

#91 Added new Casus blocks to Casus Inventory
  src/models/userModel.js
Labels: back-end, casus

#90 Production Updates
  package.json
Labels: api, back-end, front-end

#95 Casus inventory updater, Increased use of auth, Added leaderboard api, few new tank api routes
  src/backend/controllers/casusController.js
  src/backend/controllers/tankController.js
  src/backend/controllers/userController.js
  src/backend/middleware/auth.js
  src/backend/routes/casusRoutes.js
  src/backend/routes/tankRoutes.js
  src/backend/routes/userRoutes.js
  src/backend/server.js
  src/login/SignupPopup.js
  src/models/userModel.js
Labels: api

#101 Added tankComponents inventory.
  src/models/userModel.js
Labels: back-end, casus
